#ifndef SHARED_H
#define SHARED_H

#define VERSION "0.0.1a"
#define TIMELINE_PORT 50182
#define MAX_PACKET_SIZE 256 * 1024 //Taille maximum des données dans FILE_DATA
#define nbr(x) QString::number(x)

enum Error
{
    SERR_INVALID_VERSION = 0,
    SERR_COULDNT_CREATE_FILE,
    SERR_TRANSFER_IN_PROGESS
};

enum OpCodeValues
{
    CMSG_HELLO = 0,
    SMSG_HELLO,
    SMSG_ERROR,
    SMSG_KICK,
    CMSG_NEW_BACKUP,
    CMSG_INITIATE_TRANSFER,
    CMSG_FINISH_TRANSFER,
    CMSG_CANCEL_TRANSFER,
    CMSG_FILE_DATA,
    SMSG_WAITING_FOR_DATA,
    SMSG_TRANSFER_COMPLETE,
    CMSG_DELETE_FILE,
    SMSG_FILE_DELETED,
    CMSG_FILE_LIST,
    SMSG_FILE_LIST
};

#define NB_OPCODES 15

#endif // SHARED_H
